# .github/workflows/success-message.yml
name: Success Message Only

on:
  push:
    branches:
      - main  # Or any branch you want this to trigger on

jobs:
  print-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run success message
        run: echo "✅ Pipeline ran successfully!"
